### ISSUE TITLE
Manage Balance Not Working

### ISSUE THREAD

**Issue by nanaasar** [RashminDungrani/online-banking#4] opened 2022-02-08 15:33 UTC
Thanks for the good job Rashmin, however I'm facing a little change and would need your help.

under the Manage balance tab, when I press Add balance [ex 1000] it doesn't update the database but the reduce balance works.

**Comment by RashminDungrani** [comment] 2023-04-09 04:43
duplicate of #3

Please reopen this if that conversation would not help.

**Closed as completed** 2023-04-09 04:43 UTC
